export const COLORS = {
  primary: "#004ac6",
  primaryContainer: "#2563eb",
  primaryFixed: "#dbe1ff",
  secondary: "#455f87",
  secondaryContainer: "#b5d0fd",
  tertiary: "#005a82",
  tertiaryFixed: "#c9e6ff",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  surface: "#f7f9fb",
  onSurface: "#191b23",
  onSurfaceVariant: "#434655",
  outlineVariant: "#c3c6d7",
  surfaceContainerLow: "#f3f3fe",
  background: "#faf8ff",
  navDark: "#1E3A5F",
  success: "#16a34a",
  successContainer: "#dcfce7",
};

export const INIT_TICKETS_HILANG = [
  {
    id: "TK-2024-0082", type: "hilang",
    nama: "Budi Santoso", nim: "G641200XX", phone: "081234567890",
    item: "MacBook Pro M2 - Space Gray",
    location: "Perpustakaan LSI, Lantai 2", time: "12 Mei 2024, 10:30",
    status: "menunggu", color: "Abu-abu", category: "Elektronik",
    desc: "Laptop silver dengan stiker di pojok kanan bawah, model M2 Pro. Ada charger berwarna putih di dalam tas laptop berwarna hitam. Ciri khas: ada nama 'Budi' yang ditulis di bagian belakang charger.",
    img: "https://media.studio7thailand.com/66407/MacBook_Pro_13-inch_Space_Gray_2-square_medium.jpg",
    studentConfirm: false, adminConfirm: false, catatan: "",
  },
  {
    id: "TK-2024-0080", type: "hilang",
    nama: "Ahmad Fakhri", nim: "F341900XX", phone: "082345678901",
    item: "Dompet Kulit Coklat",
    location: "Kantin Agribisnis, Meja pojok", time: "11 Mei 2024, 13:00",
    status: "diproses", color: "Coklat", category: "Dompet & Tas",
    desc: "Dompet kulit coklat berisi KTM, SIM, dan beberapa kartu ATM. Ada foto keluarga di dalamnya. Dompet agak tebal dan ada logo merek di bagian depan.",
    img: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=300&fit=crop",
    studentConfirm: false, adminConfirm: false, catatan: "Sedang dicek di area kantin.",
  },
  {
    id: "TK-2024-0078", type: "hilang",
    nama: "Rina Wati", nim: "H241800XX", phone: "083456789012",
    item: "iPhone 13 Pro Max",
    location: "Gedung GWW, Lantai 3 Ruang 302", time: "10 Mei 2024, 15:45",
    status: "menunggu", color: "Biru Sierra", category: "Elektronik",
    desc: "iPhone 13 Pro Max warna biru sierra, ada case transparan dengan gantungan kunci kecil berbentuk bintang. Wallpaper foto gunung.",
    img: "https://s13emagst.akamaized.net/products/40685/40684428/images/res_0527b4f237cdaab2544c0f8e58980ac9.jpg",
    studentConfirm: false, adminConfirm: false, catatan: "",
  },
];

export const INIT_TICKETS_TEMUAN = [
  {
    id: "TK-2024-0081", type: "temuan",
    nama: "Siti Rahayu", nim: "H441900XX", phone: "082345678901",
    item: "Kacamata Frame Gold",
    location: "Taman Rektorat, Bangku dekat kolam", time: "12 Mei 2024, 09:00",
    status: "menunggu", color: "Emas", category: "Aksesori",
    desc: "Kacamata bingkai emas ditemukan di bangku taman dekat kolam, tanpa case. Lensa minus tipis.",
    img: "https://yogyaku.com/wp-content/uploads/2022/06/goods_447018_sub19.webp",
    studentConfirm: false, adminConfirm: false, catatan: "",
  },
  {
    id: "TK-2024-0079", type: "temuan",
    nama: "Dewi Anjani", nim: "G141800XX", phone: "083456789012",
    item: "Tas Ransel Hitam Jansport",
    location: "Gedung GWW, Lobi Lantai 1", time: "11 Mei 2024, 14:00",
    status: "menunggu", color: "Hitam", category: "Dompet & Tas",
    desc: "Tas ransel hitam merek Jansport, berisi beberapa buku catatan, alat tulis, dan pulpen biru. Ada kartu nama di kantong depan.",
    img: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop",
    studentConfirm: false, adminConfirm: false, catatan: "",
  },
  {
    id: "TK-2024-0077", type: "temuan",
    nama: "Rizki Pratama", nim: "F341700XX", phone: "084567890123",
    item: "Kunci Motor Honda",
    location: "Parkiran Faperta, Dekat gerbang masuk", time: "10 Mei 2024, 08:30",
    status: "diterima", color: "Hitam", category: "Kunci",
    desc: "Kunci motor Honda dengan gantungan kunci berbentuk bola basket kecil berwarna oranye. Kunci sudah berada di pos keamanan Faperta.",
    img: "https://lzd-img-global.slatic.net/g/p/a44e991b826e567e9bca7aab703308e7.jpg_720x720q80.jpg_.webp",
    studentConfirm: false, adminConfirm: false, catatan: "Barang aman di pos keamanan Faperta.",
  },
];

export const INIT_POSTINGAN = [
  {
    id: "POST-001", type: "hilang",
    item: "MacBook Pro M2 - Space Gray",
    location: "Perpustakaan LSI", time: "2 jam yang lalu",
    status: "diproses", color: "Abu-abu", category: "Elektronik",
    desc: "Laptop silver dengan stiker di pojok kanan bawah, model M2 Pro. Ada charger putih di dalam tas hitam.",
    img: "https://media.studio7thailand.com/66407/MacBook_Pro_13-inch_Space_Gray_2-square_medium.jpg",
  },
  {
    id: "POST-002", type: "temuan",
    item: "Kunci Motor Honda",
    location: "Parkiran Faperta", time: "1 hari yang lalu",
    status: "menunggu", color: "Hitam", category: "Kunci",
    desc: "Kunci motor Honda dengan gantungan kunci berbentuk bola basket, ditemukan di area parkir. Silakan klaim ke pos keamanan.",
    img: "https://lzd-img-global.slatic.net/g/p/a44e991b826e567e9bca7aab703308e7.jpg_720x720q80.jpg_.webp",
    ticketId: "TK-2024-0077",
  },
  {
    id: "POST-003", type: "hilang",
    item: "Dompet Kulit Coklat",
    location: "Kantin Agribisnis", time: "2 hari yang lalu",
    status: "selesai", color: "Coklat", category: "Dompet & Tas",
    desc: "Dompet kulit coklat berisi KTM dan beberapa kartu. Jika menemukan harap segera hubungi pos keamanan.",
    img: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=300&fit=crop",
    ticketId: "TK-2024-0080",
  },
  {
    id: "POST-004", type: "temuan",
    item: "Kacamata Frame Gold",
    location: "Taman Rektorat", time: "5 jam yang lalu",
    status: "menunggu", color: "Emas", category: "Aksesori",
    desc: "Kacamata bingkai emas ditemukan di bangku taman, tanpa case. Barang di pos keamanan rektorat.",
    img: "https://yogyaku.com/wp-content/uploads/2022/06/goods_447018_sub19.webp",
    ticketId: "TK-2024-0081",
  },
];